-- https://github.com/nvim-neo-tree/neo-tree.nvim
-- vim.keymap.set('n', '<C-f>', '<cmd>NeoTreeShowToggle<CR>');
-- vim.keymap.set('n', '<leader>fb', '<cmd>NeoTreeFloatToggle<CR>');
-- vim.keymap.set('n', '<leader>ff', ':Neotree ');
