- hosts: all
  become: 'yes'
  vars:
    packages:
      - vim
      - wget
      - curl
      - htop
  tasks:
    - name: Ensure a list of packages installed
      apt:
        name: '"{{ packages }}"'
        state: present
    - name: All done!
      debug:
        msg: Packages have been succssfully installede
